[package]
name = "kafka-research"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
anyhow = "1"
rdkafka = "0.36"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

#snarkvm = "1"